import { createServerClient } from '@/lib/supabase-server';
import { LogoutButton } from '@/components/AuthButton';
import Link from 'next/link';
export default async function Dashboard(){
 const supabase=await createServerClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user) return null;
 const {data:profile}=await supabase.from('profiles').select('*').eq('id',user.id).single();
 const {data:subjects}=await supabase.from('subjects').select('*').order('name');
 const {data:tasks}=await supabase.from('tasks').select('*').eq('completed',false).order('due_at',{ascending:true}).limit(5);
 return <main className="mx-auto max-w-6xl p-6"><header className="flex items-center justify-between"><div><p className="text-sm text-emerald-700 font-semibold">Perfil: {profile?.learning_profile ?? 'padrao'}</p><h1 className="text-3xl font-bold">Painel de estudos</h1></div><LogoutButton/></header><section className="mt-8 grid gap-4 md:grid-cols-3"><Link className="card p-5 hover:border-emerald-400" href="/biblioteca"><h2 className="font-bold">Biblioteca médica</h2><p className="text-sm text-slate-600">Matérias, tópicos, subtópicos e questões.</p></Link><Link className="card p-5 hover:border-emerald-400" href="/tarefas"><h2 className="font-bold">Tarefas e lembretes</h2><p className="text-sm text-slate-600">Crie revisões e receba e-mail.</p></Link><Link className="card p-5 hover:border-emerald-400" href="/perfil"><h2 className="font-bold">Acessibilidade cognitiva</h2><p className="text-sm text-slate-600">TDAH, TEA, dislexia ou padrão.</p></Link></section><section className="mt-8 grid gap-6 md:grid-cols-2"><div className="card p-5"><h2 className="text-xl font-bold">Matérias</h2><ul className="mt-4 space-y-2">{subjects?.map(s=><li key={s.id} className="rounded-lg bg-slate-50 p-3"><b>{s.name}</b><p className="text-sm text-slate-600">{s.description}</p></li>)}</ul></div><div className="card p-5"><h2 className="text-xl font-bold">Próximas tarefas</h2><ul className="mt-4 space-y-2">{tasks?.length?tasks.map(t=><li key={t.id} className="rounded-lg bg-slate-50 p-3"><b>{t.title}</b><p className="text-sm text-slate-600">{t.due_at?new Date(t.due_at).toLocaleString('pt-BR'):'Sem prazo'}</p></li>):<p className="text-slate-600">Nenhuma tarefa pendente.</p>}</ul></div></section></main>
}
